- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: yes
- name: Run the equivalent of "apt-get clean" as a separate step
  ansible.builtin.apt:
    clean: yes
